apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: immediate-anglerfish-nodejs 
  janus-idp.io/tekton: immediate-anglerfish-nodejs
  backstage.io/kubernetes-id: immediate-anglerfish-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: immediate-anglerfish-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  