apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: immediate-anglerfish-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: immediate-anglerfish-nodejs 
  name: immediate-anglerfish-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: immediate-anglerfish-nodejs 
